### ISSUE TITLE
purrr 1.0.0 revdep tracking

### ISSUE THREAD

**Issue by hadley** [tidyverse/purrr#969]
* [x] https://github.com/larmarange/broom.helpers — pluck returns 0 length vector (in `.get_min_version_required()`)
  * [x] https://github.com/ddsjoberg/gtsummary — fixed with dev broom.helpers
* [x] https://github.com/bfgray3/cattonum — https://github.com/bfgray3/cattonum/pull/68
* [x] https://github.com/zajichek/cheese — https://github.com/zajichek/cheese/pull/2
* [x] https://github.com/rstudio/connectapi — https://github.com/rstudio/connectapi/pull/176
* [x] https://github.com/Robsteranium/csvwr — https://github.com/Robsteranium/csvwr/pull/6
* [x] https://github.com/openpharma/DataFakeR — https://github.com/openpharma/DataFakeR/pull/4
* [x] https://github.com/UchidaMizuki/dibble — https://github.com/UchidaMizuki/dibble/pull/9
* [x] https://github.com/ffverse/ffscrapr —  https://github.com/ffverse/ffscrapr/pull/383
* [x] https://github.com/chjackson/flexsurv-dev — https://github.com/chjackson/flexsurv-dev/pull/147
* [x] https://github.com/rangi513/grizbayr — https://github.com/rangi513/grizbayr/pull/2
* [x] https://github.com/ramiromagno/gwasrapidd — https://github.com/ramiromagno/gwasrapidd/pull/37
* [x] https://github.com/HealthCatalyst/healthcareai-r — https://github.com/HealthCatalyst/healthcareai-r/pull/1302
* [x] https://github.com/levisc8/ipmr — https://github.com/levisc8/ipmr/pull/67
* [x] https://github.com/MatthewHeun/RCLabels — https://github.com/MatthewHeun/RCLabels/pull/1
* [x] https://github.com/PublicHealthEngland/PHEindicatormethods — https://github.com/publichealthengland/PHEindicatormethods/pull/69
* [x] https://github.com/fdavidcl/ruta — https://github.com/fdavidcl/ruta/pull/46
* [x] https://github.com/GrossSBM/sbm — https://github.com/GrossSBM/sbm/pull/8
* [x] https://github.com/zff-excellent/scImmuneGraph — https://github.com/zff-excellent/scImmuneGraph/issues/1
* [x] https://github.com/statisfactions/simpr — https://github.com/statisfactions/simpr/pull/73
* [x] https://github.com/ropensci/skimr — https://github.com/ropensci/skimr/pull/716
* [x] https://github.com/tidymodels/tidypredict — https://github.com/tidymodels/tidypredict/pull/111
* [x] https://github.com/efinite/utile.tools — https://github.com/efinite/utile.tools/pull/1

## New 2022-11-02

* [x] https://github.com/apache/arrow — https://github.com/apache/arrow/pull/14581
* [x] https://github.com/cran/naive — emailed 2022-11-02
* [x] https://github.com/mps9506/rATTAINS — https://github.com/mps9506/rATTAINS/pull/26 + tidyjson
* [x] https://github.com/colearendt/tidyjson — https://github.com/colearendt/tidyjson/pull/140

# Fixed

* [x] https://github.com/mevers/allhomes — https://github.com/mevers/allhomes/pull/5
* [x] https://github.com/rubenarslan/codebook — https://github.com/rubenarslan/codebook/issues/73
* [x] https://github.com/hadley/cubelyr — mapping a quosure
* [x] https://github.com/DanChaltiel/crosstable — #993
* [x] https://github.com/yutannihilation/gghighlight — https://github.com/yutannihilation/gghighlight/issues/186
* [x] https://github.com/shannonpileggi/gtreg — #991
* [x] https://github.com/uribo/jpmesh — #987
* [x] https://github.com/dmphillippo/multinma — https://github.com/dmphillippo/multinma/issues/20
* [x] https://github.com/ashbythorpe/nestedmodels — https://github.com/ashbythorpe/nestedmodels/pull/1
* [x] https://github.com/UchidaMizuki/partialised — https://github.com/UchidaMizuki/partialised/issues/1
* [x] https://github.com/psychmeta/psychmeta — #993
* [x] https://github.com/ludvigolsen/rearrr — https://github.com/LudvigOlsen/rearrr/issues/1
* [x] https://github.com/tidymodels/recipes — https://github.com/tidymodels/recipes/pull/1052
* [x] https://github.com/lhdjung/scrutiny — https://github.com/lhdjung/scrutiny/pull/24/
* [x] https://github.com/kcf-jackson/sketch — https://github.com/kcf-jackson/sketch/issues/19
* [x] https://github.com/MSKCC-Epi-Bio/tidycmprsk — https://github.com/MSKCC-Epi-Bio/tidycmprsk/pull/87
* [x] https://github.com/juliasilge/tidytext — #981
* [x] https://github.com/EDJNet/tidywikidatar — https://github.com/EDJNet/tidywikidatar/pull/5
